---

- hosts: all
  become: true
  tasks:


  - name: "Update all"
    tags: always
    package:
      update_only: yes
      update_cache: yes

- hosts: virt1
  become: true
  tasks:

  - name: "install neofetch on virt1"
    tags: virt1,neofetch
    package:
      name: 
        - neofetch
      state: latest

- hosts: virt2
  become: true
  tasks:

  - name: "install cowsay on virt2"
    tags: virt2,cowsay
    package:
      name:
        - cowsay
      state: latest
