---

- hosts: all
  become: true
  tasks:

  - name: "remove neofetch & cowsay"
    package:
      name: 
        - "{{ neofetch_package }}"
        - "{{ cowsay_package }}"
      state: absent
      update_cache: yes
